version: '3'
services:
  app:
    image: node:14.5
    working_dir: /app
    command: bash -c "npm install && npm start"
    ports:
      - '3000:3000'
    volumes:
      - ./:/app/
    environment:
      - CHOKIDAR_USEPOLLING=true